---
title: Blog W.W.W
timezone: UTC
collections:
  events:
    title: Events
    output: true
    permalink: "/events/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Wild Wide West - Communauté Technique Ouest - Softeam Digital
show_downloads: false
baseurl: ''
url: https://softeamouest.github.io
cayman-blog:
  date_format: "%b %-d, %Y"
theme: 
author: Mehdi EL KOUHEN
image: "/thumbnail-jumbo.png"
paginate: 5
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-toc
